spring:
  application:
    name: foodcore-order

  threads:
    virtual:
      enabled: true

  # Perfil padrão (development)
  profiles:
    active: local

  # Configurações de banco de dados
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  # Spring Clouud
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 500
            readTimeout: 2000
    kubernetes:
      discovery:
        namespaces:
          - catalog
          - payment
      # https://kubernetes.io/docs/concepts/services-networking/service/#cloud-native-service-discovery
      use-endpoint-slices: true

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          jdbc:
            time_zone: UTC
      show-sql: false

  # Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: prod # Contexto padrão é prod (será sobrescrito em local)

  # SpringDoc
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha
      disable-swagger-default-url: true
      doc-expansion: none
      show-actuator: true

  # Upload de arquivos
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  # Spring SMTP
  mail:
    host: ${SPRING_MAIL_HOST:}
    port: ${SPRING_MAIL_PORT:}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWD:}
    properties:
      mail.smtp.auth: ${SPRING_MAIL_AUTH_ENABLED:}
      mail.smtp.starttls.enable: ${SPRING_MAIL_TLS_ENABLED:}

# Circuit Breaker
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true

aws:
  cognito:
    aws-credentials: ${AWS_CREDENTIALS:}
    userPoolId: ${AWS_COGNITO_USER_POOL_ID:}
    endpoint: ${AWS_COGNITO_ENDPOINT:}

azsvcbus:
  connection-string: ${AZ_SVC_BUS_CONNECTION_STRING:}

management:
  # Tracing Distribuído
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:}/api/v2/spans

# Configurações de logging
logging:
  level:
    root: INFO
    com.soat.fiap.food.core.api: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springdoc: DEBUG

server:
  address: ${SERVER_ADDRESS:}
  port: ${SERVER_PORT:}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:}
  compression:
    enabled: true
  error:
    include-message: always
    include-binding-errors: always

# Microsserviços
catalog:
  service:
    name: ${CATALOG_MS_SERVICE_NAME:}
    url: http://${CATALOG_MS_HOSTNAME:}${server.servlet.context-path}

payment:
  service:
    name: ${PAYMENT_MS_SERVICE_NAME:}
    url: http://${PAYMENT_MS_HOSTNAME:}${server.servlet.context-path}
