apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "api.fullname" . }}-cluster-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods", "endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]