apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "api.fullname" . }}-role-binding
  namespace: {{ .Values.namespace.api.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "api.fullname" . }}-sa
  namespace: {{ .Values.namespace.api.name }}
roleRef:
  kind: ClusterRole
  name: {{ include "api.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "api.fullname" . }}-role-binding
  namespace: {{ .Values.namespace.catalog.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "api.fullname" . }}-sa
  namespace: {{ .Values.namespace.api.name }}
roleRef:
  kind: ClusterRole
  name: {{ include "api.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "api.fullname" . }}-role-binding
  namespace: {{ .Values.namespace.payment.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "api.fullname" . }}-sa
  namespace: {{ .Values.namespace.api.name }}
roleRef:
  kind: ClusterRole
  name: {{ include "api.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io