apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "api.fullname" . }}-secrets-crd
  namespace: {{ .Values.namespace.api.name }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "api.fullname" . }}-secrets
      type: Opaque
      data:
        - objectName: pgsql-jdbc-url-order
          key: SPRING_DATASOURCE_URL

        - objectName: pgsql-username-order
          key: SPRING_DATASOURCE_USERNAME

        - objectName: pgsql-password-order
          key: SPRING_DATASOURCE_PASSWORD

        - objectName: aws-credentials
          key: AWS_CREDENTIALS

        - objectName: aws-cognito-user-pool-id
          key: AWS_COGNITO_USER_POOL_ID

        - objectName: az-svc-bus-connection-string
          key: AZ_SVC_BUS_CONNECTION_STRING

        - objectName: server-mail-username
          key: SPRING_MAIL_USERNAME

        - objectName: server-mail-password
          key: SPRING_MAIL_PASSWORD

        - objectName: server-mail-host
          key: SPRING_MAIL_HOST

        - objectName: server-mail-port
          key: SPRING_MAIL_PORT
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secrets.azureKeyVault.clientID }}
    keyvaultName: {{ .Values.secrets.azureKeyVault.keyVaultName }}
    tenantId: {{ .Values.secrets.azureKeyVault.tenantId }}
    objects: |
      array:
        - |
            objectName: pgsql-jdbc-url-order
            objectType: secret
        - |
            objectName: pgsql-username-order
            objectType: secret
        - |
            objectName: pgsql-password-order
            objectType: secret
        - |
            objectName: aws-credentials
            objectType: secret
        - |
            objectName: aws-cognito-user-pool-id
            objectType: secret
        - |
            objectName: az-svc-bus-connection-string
            objectType: secret
        - |
            objectName: server-mail-username
            objectType: secret
        - |
            objectName: server-mail-password
            objectType: secret
        - |
            objectName: server-mail-host
            objectType: secret
        - |
            objectName: server-mail-port
            objectType: secret