# DNS Alias para services em outros namespaces, utilizados pelo Ingress
{{- if .Values.ingress.enabled }}
{{- $services := (include "ingress.services" $ | fromYamlArray) }}
{{- range $svc := $services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
spec:
  type: ExternalName
  externalName: "{{ $svc.name }}.{{ $svc.namespace }}.svc.cluster.local" # "svc.cluster.local" - sufixo padrão do k8s para serviços internos dentro do cluster
  ports:
    - port: {{ $svc.port }}
---
{{- end }}
{{- end }}